#!/bin/bash


function get(){
    kubectl api-resources --verbs=list --namespaced -o name   | \
        xargs -n 1 kubectl get \ 
            --no-headers --output name  --show-kind --ignore-not-found -n $1

}

 
if [[ $1 == "" ]]
then
    echo "[ERROR] please add a namespace"
    echo "Usage: $0 < namespace > " 
    exit 1
fi


if ( oc get ns $1 >/dev/null 2>&1 )
then
    echo "[INFO] getting resources in $1. please wait..."
    get $1
else
    echo "[ERROR] namespace - $1 not found."
    exit 1
fi